language: java

jdk:
 - oraclejdk8
 - openjdk8
 
before_install:
 - chmod +x gradlew

install:
 - ./gradlew assemble -x signArchives

script:
 - ./gradlew check -x signArchives
 - ./gradlew codeCoverageReport
 
after_success:
 - bash <(curl -s https://codecov.io/bash)
